# Archivo de configuración para Nixpacks (Versión Corregida)

[phases.install]
# 1. Instala las dependencias de PHP
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
# 2. Prepara el archivo de entorno .env
# 3. Genera la clave de aplicación de Laravel
# 4. Cachea la configuración para producción
cmds = ["cp .env.example .env", "php artisan key:generate --force", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

# 3. NO añadimos la sección [start]
# Dejamos que Nixpacks use su comando de arranque por defecto para Laravel,
# que sabe cómo iniciar el servidor web correctamente.