# Archivo de configuración para Nixpacks

[phases.install]
# Comando para instalar las dependencias de Composer
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
# Comandos para preparar Laravel para producción
cmds = ["php artisan key:generate --force", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
# Comando para iniciar el servidor web (Nginx y PHP-FPM)
cmd = "nginx -c /app/nginx.conf & php-fpm"