# Archivo de configuración para Nixpacks (v7 - Usando Artisan Serve)

[phases.setup]
# Pedimos nodejs_20 para que coincida con lo que pide Vite
nixPkgs = [
    '(php.withExtensions (pe: pe.enabled ++ []))',
    'libmysqlclient',
    'phpPackages.composer',
    'nodejs_20',  # <-- ACTUALIZADO DE 18 A 20
    'npm-9_x'
]
nixLibs = ['libmysqlclient']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'e24b4c09e963677b1beea49d411cd315a024ad3a'
aptPkgs = ["curl", "wget"]

[phases.install]
# 1. Instala dependencias PHP y Node.js
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install"
]

[phases.build]
# 2. Compila frontend y prepara Laravel
cmds = [
    "npm run build",
    "cp .env.example .env",
    "php artisan key:generate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "chown -R nobody:nogroup /app/storage /app/bootstrap/cache",
    "chmod -R 775 /app/storage /app/bootstrap/cache"
]

[start]
# 3. Usa el servidor de Laravel en el puerto 8000, que es lo que Coolify espera
cmd = "php artisan serve --host=0.0.0.0 --port=8000"