# Nixpacks.toml
providers = ["php"]

[phases.setup]
nixPkgs = [
  "php83", "composer",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.opcache"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
# Para test/arranque simple. Para prod serio, usa Apache/Nginx+php-fpm.
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"